/* Quiet Luxury Editorial: the dashboard is a service console rather than a generic admin grid—warm side navigation, readable activity, clear next steps, and low-noise state changes. */
import { Bell, CalendarDays, Check, ChevronRight, Clock3, Heart, Headset, Home, LayoutGrid, Mail, Plus, Settings, ShieldCheck, SlidersHorizontal, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { SiteHeader } from "@/components/SiteChrome";
import { PropertyCard } from "@/components/PropertyCard";
import { rentals } from "@/data/rentals";
import { useSavedProperties } from "@/contexts/SavedPropertiesContext";

type Section = "Dashboard" | "My rentals" | "Favorites" | "Messages" | "Settings";

const navItems: { label: Section; icon: typeof LayoutGrid }[] = [
  { label: "Dashboard", icon: LayoutGrid }, { label: "My rentals", icon: Home }, { label: "Favorites", icon: Heart }, { label: "Messages", icon: Mail }, { label: "Settings", icon: Settings },
];

export default function Dashboard() {
  const [section, setSection] = useState<Section>("Dashboard");
  const [calendarOpen, setCalendarOpen] = useState(false);
  const [ownerOpen, setOwnerOpen] = useState(false);
  const [contactOpen, setContactOpen] = useState(false);

  return <div className="dashboard-shell"><SiteHeader /><div className="dashboard-frame"><aside className="dashboard-sidebar"><div className="dashboard-profile"><img src="/hearthline/agent-eleanor_8f7ff510.jpg" alt="Member profile" /><div><strong>Good to see you</strong><span>Member since 2024</span></div></div><nav className="dashboard-nav" aria-label="Dashboard sections">{navItems.map(({ label, icon: Icon }) => <button key={label} type="button" className={section === label ? "dashboard-nav__item dashboard-nav__item--active" : "dashboard-nav__item"} onClick={() => setSection(label)}><Icon size={17} strokeWidth={1.75} />{label}</button>)}</nav><button type="button" className="button button--clay dashboard-owner-button" onClick={() => setOwnerOpen(true)}><Plus size={16} /> List a property</button></aside><main className="dashboard-main"><div className="dashboard-topline"><div><p className="eyebrow">Your Hearthline</p><h1 className="page-title">{section === "Dashboard" ? <>A clear view<br /><em>of what is next.</em></> : section}</h1><p className="dashboard-subtitle">{section === "Dashboard" ? "The homes, viewings, and next steps currently in motion." : section === "Favorites" ? "The places you saved for a second look." : section === "Messages" ? "A direct line to the people looking after your move." : section === "Settings" ? "Keep your account details and preferences up to date." : "The places and plans currently in motion."}</p></div><button className="icon-button dashboard-alert" type="button" onClick={() => toast("You are all caught up")} aria-label="View notifications"><Bell size={18} /><span /></button></div>{section === "Dashboard" && <Overview onCalendar={() => setCalendarOpen(true)} onContact={() => setContactOpen(true)} />}{section === "My rentals" && <MyRentals />}{section === "Favorites" && <Favorites />}{section === "Messages" && <Messages onContact={() => setContactOpen(true)} />}{section === "Settings" && <SettingsPanel />}</main></div>{calendarOpen && <CalendarPanel onClose={() => setCalendarOpen(false)} />}{ownerOpen && <OwnerDialog onClose={() => setOwnerOpen(false)} />}{contactOpen && <ContactPanel onClose={() => setContactOpen(false)} />}</div>;
}

function Overview({ onCalendar, onContact }: { onCalendar: () => void; onContact: () => void }) {
  const { saved } = useSavedProperties();
  const [activityExpanded, setActivityExpanded] = useState(false);
  const activity = [{ time: "Today, 10:30 AM", text: "Viewing confirmed for The Azure Penthouse", current: true }, { time: "Yesterday, 4:15 PM", text: "Saved Glasshouse Villa to your shortlist", current: false }, { time: "Mon, 2nd Oct", text: "Background check completed successfully", current: false }, { time: "Fri, 29th Sep", text: "Eleanor sent a lease summary", current: false }];
  return <><div className="stats-grid"><Stat icon={ShieldCheck} label="ACTIVE LEASES" value="2" note="Properties currently occupied" /><Stat icon={CalendarDays} label="UPCOMING VIEWINGS" value="3" note="Next: tomorrow at 2:00 PM" /><Stat icon={Heart} label="SAVED FAVORITES" value={String(saved.length)} note="Your shortlist, always close" /></div><div className="dashboard-content-grid"><section className="dashboard-card dashboard-rentals"><div className="dashboard-card__heading"><div><p className="eyebrow">In motion</p><h2>Upcoming rentals & viewings</h2></div><button type="button" className="text-button" onClick={onCalendar}>View calendar <ChevronRight size={15} /></button></div><RentalRow status="VIEWING SCHEDULED" statusClass="status--muted" image="/hearthline/gallery-terrace_a6d61c2e.jpg" title="The Azure Penthouse, 45th Floor" address="1200 Riverside Drive, Metropolitan Area" price="$12,500" meta="Tomorrow, 2:00 PM · 3 beds · 3.5 baths" /><RentalRow status="LEASE PENDING" statusClass="status--clay" image="/hearthline/gallery-bedroom_7474c497.jpg" title="Oakwood Modern Townhouse" address="88 Heritage Lane, Westside District" price="$8,200" meta="Awaiting signature · 2 beds · 2 baths" /></section><div className="dashboard-side-stack"><section className="dashboard-card"><div className="dashboard-card__heading"><div><p className="eyebrow">Timeline</p><h2>Recent activity</h2></div></div><ol className="activity-list">{activity.slice(0, activityExpanded ? 4 : 3).map((item, index) => <li key={item.text}><span className={`activity-dot ${item.current ? "activity-dot--active" : ""}`} />{index < (activityExpanded ? 3 : 2) && <span className="activity-line" />}<div><small>{item.time}</small><strong>{item.text}</strong></div></li>)}</ol><button type="button" className="button button--outline w-full mt-6" onClick={() => setActivityExpanded((current) => !current)}>{activityExpanded ? "Show less" : "View all activity"}</button></section><section className="concierge-card"><span className="concierge-card__icon"><Headset size={21} /></span><p className="eyebrow eyebrow--light">Here when you need us</p><h2>Dedicated concierge.</h2><p>Need help with a lease or a viewing? Eleanor is ready to help.</p><button type="button" className="button button--clay w-full" onClick={onContact}>Contact Eleanor <Mail size={15} /></button></section></div></div></>;
}

function Stat({ icon: Icon, label, value, note }: { icon: typeof ShieldCheck; label: string; value: string; note: string }) { return <div className="stat-card"><div className="stat-card__top"><span>{label}</span><Icon size={18} /></div><strong>{value}</strong><p>{note}</p></div>; }
function RentalRow({ status, statusClass, image, title, address, price, meta }: { status: string; statusClass: string; image: string; title: string; address: string; price: string; meta: string }) { return <Link href="/property" className="rental-row"><img src={image} alt="" /><div className="rental-row__copy"><div className="rental-row__top"><span className={`status ${statusClass}`}>{status}</span><strong>{price}<small>/mo</small></strong></div><h3>{title}</h3><p>{address}</p><span className="rental-row__meta"><CalendarDays size={14} /> {meta}</span></div><ChevronRight size={17} className="rental-row__arrow" /></Link>; }
function MyRentals() { return <div className="dashboard-section-stack"><section className="dashboard-card"><div className="dashboard-card__heading"><div><p className="eyebrow">In progress</p><h2>Your current homes</h2></div><span className="count-chip">2 active</span></div><RentalRow status="ACTIVE LEASE" statusClass="status--ink" image="/hearthline/gallery-terrace_a6d61c2e.jpg" title="The Azure Penthouse, 45th Floor" address="1200 Riverside Drive, Metropolitan Area" price="$12,500" meta="Lease ends 30 Sep 2027 · 3 beds · 3.5 baths" /><RentalRow status="LEASE PENDING" statusClass="status--clay" image="/hearthline/gallery-bedroom_7474c497.jpg" title="Oakwood Modern Townhouse" address="88 Heritage Lane, Westside District" price="$8,200" meta="Awaiting signature · 2 beds · 2 baths" /></section></div>; }
function Favorites() { const { saved } = useSavedProperties(); const favorites = rentals.filter((rental) => saved.includes(rental.id)); return <div className="dashboard-section-stack"><div className="favorites-grid">{favorites.length ? favorites.map((rental) => <PropertyCard rental={rental} key={rental.id} />) : <div className="empty-state"><span className="empty-state__mark">⌂</span><p className="eyebrow">Your shortlist</p><h2>Nothing saved yet.</h2><p>When a home catches your eye, save it here for a second look.</p><Link href="/listings" className="button button--ink">Browse homes <ChevronRight size={15} /></Link></div>}</div></div>; }
function Messages({ onContact }: { onContact: () => void }) { return <div className="dashboard-section-stack"><section className="dashboard-card message-card"><div className="message-card__avatar"><img src="/hearthline/agent-eleanor_8f7ff510.jpg" alt="Eleanor Vance" /><span /></div><div className="message-card__body"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Eleanor Vance · Today</p><h2>Viewing details for The Azure Penthouse</h2></div><span className="unread-chip">New</span></div><p>“I have held tomorrow at 2:00 PM for you. I will meet you in the lobby and bring a full lease summary.”</p><button type="button" className="button button--ink" onClick={onContact}>Reply to Eleanor <Mail size={15} /></button></div></section></div>; }
function SettingsPanel() { const [alerts, setAlerts] = useState(true); const [notes, setNotes] = useState(false); return <div className="dashboard-section-stack"><section className="dashboard-card settings-card"><div><p className="eyebrow">Account</p><h2>Preferences</h2></div><label className="settings-row"><span><strong>Email notifications</strong><small>Get updates about viewings and leases.</small></span><input type="checkbox" checked={alerts} onChange={(event) => { setAlerts(event.target.checked); toast(event.target.checked ? "Email notifications on" : "Email notifications off"); }} /></label><label className="settings-row"><span><strong>Monthly notes</strong><small>Receive a considered note on new places.</small></span><input type="checkbox" checked={notes} onChange={(event) => { setNotes(event.target.checked); toast(event.target.checked ? "Monthly notes on" : "Monthly notes off"); }} /></label><div className="settings-row settings-row--static"><span><strong>Profile details</strong><small>Alex Morgan · alex@example.com</small></span><button type="button" className="text-button" onClick={() => toast("Profile editor coming next")}>Edit details <ChevronRight size={15} /></button></div></section></div>; }

function CalendarPanel({ onClose }: { onClose: () => void }) { return <Overlay title="Your viewing calendar" onClose={onClose}><div className="calendar-list"><div><span>Tomorrow · 2:00 PM</span><strong>The Azure Penthouse</strong><small>1200 Riverside Drive</small></div><div><span>Thu · 11:30 AM</span><strong>Private lease consultation</strong><small>Video call with Eleanor</small></div><div><span>Next Tue · 4:15 PM</span><strong>Oakwood handover</strong><small>88 Heritage Lane</small></div></div><button type="button" className="button button--ink w-full" onClick={onClose}>Close calendar <Check size={15} /></button></Overlay>; }
function OwnerDialog({ onClose }: { onClose: () => void }) { const [sent, setSent] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); toast("Listing request received"); }; return <Overlay title={sent ? "We will take it from here." : "List a property"} onClose={onClose}>{sent ? <div className="success-state"><span><Check size={21} /></span><p>Tell us a little about the home and an owner partner will be in touch.</p><button className="button button--ink w-full" type="button" onClick={onClose}>Done <Check size={15} /></button></div> : <form className="dialog-form" onSubmit={submit}><p>Share the essentials. We will follow up with a short, human conversation—never a sales pitch.</p><label>Property address<input required placeholder="Street, city, state" /></label><label>Your email<input required type="email" placeholder="you@example.com" /></label><label>What should we know?<textarea rows={3} placeholder="Type, timing, anything distinctive..."></textarea></label><button type="submit" className="button button--clay w-full">Send property details <ArrowIcon /></button></form>}</Overlay>; }
function ContactPanel({ onClose }: { onClose: () => void }) { return <Overlay title="Talk to a real person" onClose={onClose}><div className="contact-dialog"><div className="contact-dialog__person"><img src="/hearthline/agent-eleanor_8f7ff510.jpg" alt="Eleanor Vance" /><div><h3>Eleanor Vance</h3><p>Senior Partner · New York</p></div></div><p>She can help with a lease, a viewing, or a second look at a home you saved.</p><a className="contact-row" href="mailto:hello@hearthline.example"><Mail size={17} /> hello@hearthline.example <ChevronRight size={14} /></a><a className="contact-row" href="tel:+12125550184"><Clock3 size={17} /> Usually replies within an hour <ChevronRight size={14} /></a></div></Overlay>; }
function Overlay({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="dialog-card" role="dialog" aria-modal="true" aria-label={title}><button type="button" className="dialog-close icon-button" onClick={onClose} aria-label="Close"><X size={18} /></button><p className="eyebrow">Hearthline concierge</p><h2>{title}</h2>{children}</div></div>; }
function ArrowIcon() { return <ChevronRight size={15} />; }
